"""initial migration

Revision ID: 513cf30bdf88
Revises: 
Create Date: 2022-08-13 13:46:05.248211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513cf30bdf88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('operations', 'developer', 'admin', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('developers',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('operations', 'developer', 'admin', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('operations',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('operations', 'developer', 'admin', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('workflows',
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('workflow_parameters', sa.JSON(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('workflow_name')
    )
    op.create_table('workflows_metadata',
    sa.Column('workflow_instance', sa.String(length=100), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=True),
    sa.Column('input_parameters', sa.JSON(), nullable=False),
    sa.Column('started_on', sa.DateTime(), nullable=False),
    sa.Column('ended_on', sa.DateTime(), nullable=False),
    sa.Column('logs', sa.VARCHAR(length=250), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['workflow_name'], ['workflows.workflow_name'], ),
    sa.PrimaryKeyConstraint('workflow_instance')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflows_metadata')
    op.drop_table('workflows')
    op.drop_table('operations')
    op.drop_table('developers')
    op.drop_table('admins')
    # ### end Alembic commands ###
