"""initial migration44

Revision ID: 5a5df4bc8c8b
Revises: 513cf30bdf88
Create Date: 2022-08-13 16:00:20.544281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a5df4bc8c8b'
down_revision = '513cf30bdf88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.drop_table('operations')
    op.drop_table('developers')
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('operations', 'developer', 'admin', name='userrole'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('email', name='admins_pkey')
    )
    op.create_table('developers',
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('operations', 'developer', 'admin', name='userrole'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('email', name='developers_pkey')
    )
    op.create_table('operations',
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('operations', 'developer', 'admin', name='userrole'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('email', name='operations_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
