"""add status column in workflow_metadata table

Revision ID: 77f5af4d2a02
Revises: 5a5df4bc8c8b
Create Date: 2022-08-21 20:55:55.670134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f5af4d2a02'
down_revision = '5a5df4bc8c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows_metadata', sa.Column('status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows_metadata', 'status')
    # ### end Alembic commands ###
